classDiagram
    class User {
        +Integer id
        +String name
        +String email
        +String password
        +Date createdAt
        +Date updatedAt
    }

    class Transaction {
        +Integer id
        +String description
        +Decimal amount
        +Enum type
        +Date date
        +Integer userId
    }

    class Category {
        +Integer id
        +String name
        +String color
        +Integer userId
    }

    class AuthController {
        +register(req, res, next)
        +login(req, res, next)
    }

    class TransactionController {
        +getAll(req, res, next)
        +getSummary(req, res, next)
        +create(req, res, next)
        +update(req, res, next)
        +remove(req, res, next)
        +exportPDF(req, res, next)
    }

    class CategoryController {
        +create(req, res, next)
        +getAll(req, res, next)
    }

    class PdfService {
        +generateTransactionReport(transactions)
    }

    class AuthMiddleware {
        +authMiddleware(req, res, next)
    }

    class JwtUtils {
        +generateToken(id)
        +verifyToken(token)
    }

    class CryptoUtils {
        +hashPassword(password)
        +comparePassword(pw, hash)
    }

    User "1" --> "0..*" Transaction : possui
    User "1" --> "0..*" Category : possui
    AuthController ..> User
    AuthController ..> JwtUtils
    AuthController ..> CryptoUtils
    TransactionController ..> Transaction
    TransactionController ..> PdfService
    CategoryController ..> Category
    AuthMiddleware ..> JwtUtils
